name: "push"
version: "1.0.0"
usage: "Please see https://gitlab.evertecinc.com/mi-banco/helm-pushg for usage"
description: "Push chart package to Nexus"
command: "$HELM_PLUGIN_DIR/bin/helmpush"
downloaders:
- command: "bin/helmpush"
  protocols:
  - "cm"
useTunnel: false
hooks:
  install: "cd $HELM_PLUGIN_DIR; scripts/install_plugin.sh"
  update: "cd $HELM_PLUGIN_DIR; scripts/install_plugin.sh"
